page_blocks: []

_array_structures:
 page_blocks:
  - label: Banner
    icon: article
    value: 
     _id: banner
     title: Image banner
     banner_image: 
     banner-alt-text: Test
  - label: Banner
    icon: article
    value: 
     _id: text-img.html
     title: Image banner
     banner_image: 
     banner-alt-text: Test
  